### ISSUE TITLE
any plans for housekeeping?

### ISSUE THREAD

**Issue by JannikZed** [benjamin-maynard/kubernetes-cloud-mysql-backup#13]
Hi there,
your tool sounds very promising! Until now, I'm missing any kind of housekeeping. For example, keeping only the last X backups. Are there any plans to integrate that soon?

**Comment by benjamin-maynard** [comment]
Hey @JannikZed, thanks for reaching out.

There are no plans to implement any functionality like that into the tool. As detailed in the README you should look to use lifecycle rules in GCS, or lifecycle policies in AWS to manage how long the backups are retained in the storage bucket. I don't think it would make sense to duplicate this logic and have the tool perform the housekeeping.
