### ISSUE TITLE
encrypt backups

### ISSUE THREAD

**Issue by adamdecaf** [benjamin-maynard/kubernetes-cloud-mysql-backup#15]
Thanks for this project. It's handy! Are there any plans to offer encryption prior to upload? I know the buckets can be encrypted, but uploading encrypted files helps with our compliance requirements.

**Comment by adamdecaf** [comment]
It looks like we could encrypt `/tmp/$DUMP` before calling out to `aws cp` or `gsutil cp`.

**Comment by benjamin-maynard** [comment]
Hi @adamdecaf ,

Thanks for opening this issue. I currently do not have any plans to work on adding an encryption before upload feature - but I'd be happy to implement it if you wanted to create a PR. I agree it would be useful!

**Comment by adamdecaf** [comment]
I created https://github.com/benjamin-maynard/kubernetes-cloud-mysql-backup/pull/16 which is working for me.
