### ISSUE TITLE
BACKUP_COMPRESS fail

### ISSUE THREAD

**Issue by manologarciadev** [benjamin-maynard/kubernetes-cloud-mysql-backup#17]
BACKUP_COMPRESS don't work, still upload uncompress file to GC 

`    spec:
      template:
        metadata:
          annotations:
            cattle.io/timestamp: "2020-07-10T13:36:12Z"
          creationTimestamp: null
        spec:
          containers:
          - env:
            - name: BACKUP_COMPRESS
              value: "true"
            - name: BACKUP_PROVIDER
              value: gcp
...
 image: gcr.io/maynard-io-public/kubernetes-cloud-mysql-backup
            imagePullPolicy: Always`

**Comment by benjamin-maynard** [comment]
Hi @vmga43,

I cannot reproduce this issue. Please check you are using the latest version of the container and re-open with some more detail if this is still an issue.
