### ISSUE TITLE
Upload to GCS not working

### ISSUE THREAD

**Issue by anaryk** [benjamin-maynard/kubernetes-cloud-mysql-backup#45]
Hi Everyone, I wanted to try this tool and I followed the instructions, but unfortunately I have already tried everything, but unfortunately I do not know where the error is.

`ERROR: (gcloud.auth.activate-service-account) Could not read json file /root/gcloud.json: Expecting value: line 1 column 1 (char 0)`

According to the instructions, I downloaded the json key and used base64 to encrypt and paste it into the secret. But unfortunately it doesn't work.

Thank you for your help

**Comment by benjamin-maynard** [comment]
Hi there,

What format did you download the key in from GCP? How are you encoding to base64?
