### ISSUE TITLE
Is there any reason why retention is not considered?

### ISSUE THREAD

**Issue by EugenMayer** [benjamin-maynard/kubernetes-cloud-mysql-backup#47]
Thank you for the great tooling here already, including the documentation. Worked our right of the box.

One thing i wonder is, why is there no retention configuration - seems like this is somehow not important to you?
Could you explain a bit how you deal with keeping only a hand full of backups over time?

Are you using Lifecycle management on those s3 storage?

Thanks!

**Comment by benjamin-maynard** [comment]
Hi there,

Sorry for the delay in responding. As per the README.md the recommendation is that you configure Object Versioning and Object Lifecycle Management to deal with this. These offer out of the box robust ways for you to manage retention of backups.

https://github.com/benjamin-maynard/kubernetes-cloud-mysql-backup/blob/88f60e34647bc216e7d816ac9cca31f8330d9814/README.md?plain=1#L166

https://github.com/benjamin-maynard/kubernetes-cloud-mysql-backup/blob/88f60e34647bc216e7d816ac9cca31f8330d9814/README.md?plain=1#L61
