### ISSUE TITLE
kubernetes yaml bad

### ISSUE THREAD

**Issue by moretti-zenfolio** [benjamin-maynard/kubernetes-cloud-mysql-backup#5]
error from server (Invalid): error when creating "backups.yaml": Secret "AWS_SECRET_ACCESS_KEY" is invalid: metadata.name: Invalid value: "AWS_SECRET_ACCESS_KEY": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end wit

--------
YOU MUST SEPARATE each module with "---" in your example you put "--"

**Comment by nikhleshgoenka** [comment]
Which kubernetes version are you using? Is there a hostname in your backups.yaml? Are you using FQDN for that?

**Comment by benjamin-maynard** [comment]
@moretti-zenfolio Thank you for raising this, fixed docs https://github.com/benjamin-maynard/kubernetes-s3-mysql-backup/commit/eee09a3cbc567969badefd21626d86826007abe7
