### ISSUE TITLE
iam getting Access denied error

### ISSUE THREAD

**Issue by phaniamt** [benjamin-maynard/kubernetes-cloud-mysql-backup#6]
mysqldump: Got error: 1045: "Access denied for user 'root'@'192.168.8.44' (using password: YES)" when trying to connect

**Comment by benjamin-maynard** [comment]
Hey @phaniamt 

This suggests that you are specifying the password for your database incorrectly.

**Comment by benjamin-maynard** [comment]
Hey @phaniamt : Going to close this issue as seems configuration related. Double check you have your database configuration set correctly.

Just shout me if you need any further help.
